import type React from "react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  path: string;
  tags?: string[];
}

export interface Category {
  id: string;
  name: string;
  /** Short label for dense UI (rail tooltips, chips). */
  short: string;
  description: string;
  icon: string;
  /** OKLCH hue used to tint this category's icon chip (see .cat-chip). */
  hue: number;
}

// Ordered by demand: categories contributing the most high-traffic tools
// (see POPULAR_TOOL_IDS in home-landing.tsx) come first, ties broken by size.
export const categories: Category[] = [
  {
    id: 'pdf',
    name: 'PDF Tools',
    short: 'PDF',
    description: 'Best free PDF tools online — merge, split, compress, rotate, add watermarks, page numbers, headers, and more. No sign-up required, all processing happens in your browser.',
    icon: 'FileText',
    hue: 25,
  },
  {
    id: 'image',
    name: 'Image Tools',
    short: 'Image',
    description: 'Free online image tools — image resizer, CSS grid generator, flexbox generator, SVG optimizer, color palette extractor, contrast checker, and more. No sign-up required.',
    icon: 'Image',
    hue: 320,
  },
  {
    id: 'video',
    name: 'Video Tools',
    short: 'Video',
    description: 'Free online video tools — video converter, video compressor, video trimmer, video merger, video rotator, mute video, extract audio, and more. Works entirely in your browser, no upload needed.',
    icon: 'Video',
    hue: 40,
  },
  {
    id: 'audio',
    name: 'Audio Tools',
    short: 'Audio',
    description: 'Free online audio tools — audio converter, audio trimmer, audio merger, audio compressor, volume adjuster, audio reverser, and more. No file upload to servers, all browser-based.',
    icon: 'Music',
    hue: 340,
  },
  {
    id: 'converter',
    name: 'Converters',
    short: 'Convert',
    description: 'Best free online converters — Unix timestamp, unit converter, IBAN validator, Base64, color formats, IPv4, number bases, and more. Instant results, no sign-up required.',
    icon: 'RefreshCw',
    hue: 160,
  },
  {
    id: 'text',
    name: 'Text Tools',
    short: 'Text',
    description: 'Free online text tools — word counter, case converter, text diff, lorem ipsum generator, markdown editor, slugify, and more utilities for writers, developers, and students.',
    icon: 'Type',
    hue: 240,
  },
  {
    id: 'developer',
    name: 'Developer Tools',
    short: 'Developer',
    description: 'Best free developer tools online — JSON formatter, JWT parser, regex tester, cron validator, curl converter, Docker compose generator, and more. No sign-up required, all browser-based.',
    icon: 'Code2',
    hue: 285,
  },
  {
    id: 'generator',
    name: 'Generators',
    short: 'Generate',
    description: 'Free online generator tools — UUID generator, QR code generator, password generator, Lorem Ipsum generator, barcode generator, ULID, WiFi QR, and more. Instant generation, no sign-up.',
    icon: 'Sparkles',
    hue: 140,
  },
  {
    id: 'color',
    name: 'Color Tools',
    short: 'Color',
    description: 'Free online color tools — color converter for HEX, RGB, HSL, OKLCH, LAB, and LCH. Includes color palette extractor, contrast checker, and gradient generator. No sign-up required.',
    icon: 'Palette',
    hue: 350,
  },
  {
    id: 'math',
    name: 'Math',
    short: 'Math',
    description: 'Free online math tools — calculator, percentage calculator, ETA calculator, math expression evaluator, stopwatch, datetime hub, and more. No sign-up required.',
    icon: 'Calculator',
    hue: 80,
  },
  {
    id: 'security',
    name: 'Security',
    short: 'Security',
    description: 'Free online security tools — hash generator, AES encryption, JWT generator, bcrypt, RSA key generator, password strength checker, OTP generator, and more. No sign-up required.',
    icon: 'ShieldCheck',
    hue: 15,
  },
  {
    id: 'seo',
    name: 'SEO Tools',
    short: 'SEO',
    description: 'Free online SEO tools — meta tag generator, Open Graph builder, robots.txt generator, XML sitemap creator, FAQ schema generator, keyword analyzer, URL slug generator, and more.',
    icon: 'Search',
    hue: 200,
  },
  {
    id: 'markdown',
    name: 'Markdown Tools',
    short: 'Markdown',
    description: 'Free online Markdown tools — live editor, table generator, cheatsheet, markdown-to-HTML converter, and file combiner. No sign-up required, all browser-based.',
    icon: 'BookOpen',
    hue: 260,
  },
  {
    id: 'file',
    name: 'File Tools',
    short: 'Files',
    description: 'Free online file tools — ZIP compressor, archive extractor, batch file renamer, and more. All processing happens directly in your browser, no file upload to servers.',
    icon: 'FolderOpen',
    hue: 60,
  },
];

export function getCategory(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

/** Inline style that tints `.cat-chip` elements with the category hue. */
export function categoryStyle(category?: Category | string): React.CSSProperties {
  const cat = typeof category === "string" ? getCategory(category) : category;
  return { "--cat-h": cat?.hue ?? 190 } as React.CSSProperties;
}

export const tools: Tool[] = [
  // PDF Tools
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one file',
    category: 'pdf',
    icon: 'GitMerge',
    path: '/tools/merge-pdf',
    tags: ['pdf', 'merge', 'combine', 'document', 'merge pdf online', 'combine pdf', 'join pdf', 'pdf merger', 'online pdf tools'],
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract a range of pages into a new PDF',
    category: 'pdf',
    icon: 'Scissors',
    path: '/tools/split-pdf',
    tags: ['pdf', 'split', 'extract', 'pages', 'split pdf online', 'pdf page splitter', 'extract pdf pages', 'online pdf tools'],
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate all pages in 90-degree increments',
    category: 'pdf',
    icon: 'RotateCw',
    path: '/tools/rotate-pdf',
    tags: ['pdf', 'rotate', 'orientation', 'pages', 'rotate pdf online', 'pdf page rotator', 'pdf orientation fix', 'online pdf tools'],
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove specific pages from your PDF',
    category: 'pdf',
    icon: 'Trash2',
    path: '/tools/delete-pages',
    tags: ['pdf', 'delete', 'remove', 'pages', 'delete pdf pages', 'remove pages from pdf', 'pdf page remover', 'online pdf tools'],
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Save a selection of pages as a new file',
    category: 'pdf',
    icon: 'Files',
    path: '/tools/extract-pages',
    tags: ['pdf', 'extract', 'pages', 'save', 'extract pdf pages', 'pdf page extractor', 'save pages from pdf', 'online pdf tools'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'Images to PDF',
    description: 'Convert JPG and PNG images to PDF',
    category: 'pdf',
    icon: 'ImagePlus',
    path: '/tools/jpg-to-pdf',
    tags: ['pdf', 'image', 'jpg', 'png', 'convert', 'jpg to pdf', 'png to pdf', 'image to pdf converter', 'online image to pdf', 'online pdf tools'],
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Reorder, duplicate, and preview pages',
    category: 'pdf',
    icon: 'ArrowUpDown',
    path: '/tools/organize-pdf',
    tags: ['pdf', 'organize', 'reorder', 'duplicate', 'reorder pdf pages', 'organize pdf online', 'pdf page organizer', 'online pdf tools'],
  },
  {
    id: 'add-blank-page',
    name: 'Add Blank Page to PDF',
    description: 'Insert blank pages at any position in a PDF document — choose paper size, orientation, and exact location. Free in-browser PDF editor, no upload required.',
    category: 'pdf',
    icon: 'FilePlus',
    path: '/tools/add-blank-page',
    tags: ['add blank page to pdf', 'insert blank page pdf', 'pdf add page', 'pdf editor', 'blank page', 'pdf insert', 'empty page', 'free pdf tool', 'pdf', 'page'],
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size by removing unused objects',
    category: 'pdf',
    icon: 'Zap',
    path: '/tools/compress-pdf',
    tags: ['pdf', 'compress', 'optimize', 'size', 'compress pdf online', 'reduce pdf size', 'pdf compressor', 'pdf shrink', 'online pdf tools'],
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract all text content into a plain text file',
    category: 'pdf',
    icon: 'FileText',
    path: '/tools/pdf-to-text',
    tags: ['pdf', 'text', 'extract', 'convert', 'pdf to text online', 'extract text from pdf', 'pdf text extractor', 'online pdf tools'],
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Stamp a signature image on every page',
    category: 'pdf',
    icon: 'PenTool',
    path: '/tools/sign-pdf',
    tags: ['pdf', 'sign', 'signature', 'stamp', 'sign pdf online', 'pdf signature', 'digital signature pdf', 'online pdf signer'],
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Trim margins by setting new page dimensions',
    category: 'pdf',
    icon: 'Crop',
    path: '/tools/crop-pdf',
    tags: ['pdf', 'crop', 'trim', 'margins', 'crop pdf online', 'trim pdf margins', 'pdf cropper', 'online pdf tools'],
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Stamp text or image across all pages',
    category: 'pdf',
    icon: 'Stamp',
    path: '/tools/add-watermark',
    tags: ['pdf', 'watermark', 'stamp', 'overlay', 'add watermark to pdf', 'pdf watermark online', 'watermark pdf', 'online pdf tools'],
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Insert Page X of Y at any position',
    category: 'pdf',
    icon: 'ListOrdered',
    path: '/tools/page-numbers',
    tags: ['pdf', 'page', 'numbers', 'pagination', 'add page numbers to pdf', 'pdf page numbers', 'pdf pagination', 'online pdf tools'],
  },
  {
    id: 'invert-colors',
    name: 'Invert Colors',
    description: 'Create a dark mode version of your PDF',
    category: 'pdf',
    icon: 'Contrast',
    path: '/tools/invert-colors',
    tags: ['pdf', 'invert', 'dark', 'mode', 'colors', 'invert pdf colors', 'pdf dark mode', 'pdf color inverter', 'online pdf tools'],
  },
  {
    id: 'header-footer',
    name: 'Header & Footer',
    description: 'Add custom text to top and bottom of pages',
    category: 'pdf',
    icon: 'Heading',
    path: '/tools/header-footer',
    tags: ['pdf', 'header', 'footer', 'text', 'add header to pdf', 'add footer to pdf', 'pdf header footer', 'online pdf tools'],
  },
  {
    id: 'remove-blank-pages',
    name: 'Remove Blank Pages',
    description: 'Automatically detect and delete blank pages',
    category: 'pdf',
    icon: 'FileMinus',
    path: '/tools/remove-blank-pages',
    tags: ['pdf', 'blank', 'remove', 'pages', 'remove blank pages pdf', 'delete blank pages pdf', 'auto remove blank pages', 'online pdf tools'],
  },
  {
    id: 'scanner-effect',
    name: 'Scanner Effect',
    description: 'Make your PDF look like a scanned document',
    category: 'pdf',
    icon: 'ScanLine',
    path: '/tools/scanner-effect',
    tags: ['pdf', 'scan', 'effect', 'noise', 'scanner effect pdf', 'make pdf look scanned', 'scanned document effect', 'online pdf tools'],
  },
  {
    id: 'adjust-colors',
    name: 'Adjust Colors',
    description: 'Fine-tune brightness, contrast, saturation and more',
    category: 'pdf',
    icon: 'SlidersHorizontal',
    path: '/tools/adjust-colors',
    tags: ['pdf', 'color', 'brightness', 'contrast', 'adjust pdf colors', 'pdf color editor', 'pdf brightness contrast', 'online pdf tools'],
  },
  {
    id: 'background-color',
    name: 'Background Color',
    description: 'Change the background color of your PDF',
    category: 'pdf',
    icon: 'Palette',
    path: '/tools/background-color',
    tags: ['pdf', 'background', 'color', 'fill', 'change pdf background color', 'pdf background', 'pdf color fill', 'online pdf tools'],
  },
  {
    id: 'remove-annotations',
    name: 'Remove Annotations',
    description: 'Strip comments, highlights, and links',
    category: 'pdf',
    icon: 'Eraser',
    path: '/tools/remove-annotations',
    tags: ['pdf', 'annotations', 'remove', 'clean', 'remove pdf annotations', 'delete comments from pdf', 'pdf annotation remover', 'online pdf tools'],
  },
  {
    id: 'edit-bookmarks',
    name: 'Edit Bookmarks',
    description: 'Add, edit, import, delete and extract PDF bookmarks',
    category: 'pdf',
    icon: 'Bookmark',
    path: '/tools/edit-bookmarks',
    tags: ['pdf', 'bookmarks', 'outline', 'navigation', 'edit pdf bookmarks', 'pdf bookmark editor', 'manage pdf bookmarks', 'online pdf tools'],
  },
  {
    id: 'table-of-contents',
    name: 'Table of Contents',
    description: 'Generate a table of contents page from PDF bookmarks',
    category: 'pdf',
    icon: 'List',
    path: '/tools/table-of-contents',
    tags: ['pdf', 'toc', 'bookmarks', 'contents', 'pdf table of contents', 'generate pdf toc', 'pdf bookmarks toc', 'online pdf tools'],
  },
  {
    id: 'add-page-labels',
    name: 'Add Page Labels',
    description: 'Apply PDF page labels with Roman numerals, prefixes, and custom starts',
    category: 'pdf',
    icon: 'Type',
    path: '/tools/add-page-labels',
    tags: ['pdf', 'labels', 'page', 'roman', 'add page labels pdf', 'pdf page numbering', 'roman numeral pdf', 'online pdf tools'],
  },

  // Developer Tools
  {
    id: 'modern-color',
    name: 'Modern Color Converter',
    description: 'Convert between HEX, RGB, HSL, OKLCH, LAB, and LCH',
    category: 'color',
    icon: 'Pipette',
    path: '/tools/modern-color',
    tags: ['color', 'hex', 'rgb', 'hsl', 'oklch', 'lab', 'lch', 'modern color converter', 'oklch converter', 'lab color converter', 'lch color converter', 'advanced color converter'],
  },
  {
    id: 'media-query',
    name: 'Media Query Generator',
    description: 'Generate responsive CSS breakpoints',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/media-query',
    tags: ['css', 'media', 'query', 'responsive', 'breakpoint'],
  },
  {
    id: 'data-uri',
    name: 'Data URI Maker',
    description: 'Convert files to Base64 Data URIs for CSS',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/data-uri',
    tags: ['data', 'uri', 'base64', 'css', 'embed'],
  },
  {
    id: 'barcode-studio',
    name: 'Barcode Studio',
    description: 'Generate Code128, EAN, UPC barcodes',
    category: 'generator',
    icon: 'Barcode',
    path: '/tools/barcode-studio',
    tags: ['barcode', 'ean', 'upc', 'code128', 'retail', 'barcode generator', 'free barcode generator', 'online barcode maker', 'ean barcode generator', 'upc barcode generator'],
  },
  {
    id: 'web-vitals',
    name: 'Web Vitals Simulator',
    description: 'Estimate Core Web Vitals scores',
    category: 'developer',
    icon: 'Gauge',
    path: '/tools/web-vitals',
    tags: ['web', 'vitals', 'lcp', 'fid', 'cls', 'performance'],
  },
  {
    id: 'json-sql-schema',
    name: 'JSON to SQL Schema',
    description: 'Inferred SQL table definitions from JSON',
    category: 'developer',
    icon: 'Database',
    path: '/tools/json-sql-schema',
    tags: ['json', 'sql', 'schema', 'database', 'json to sql schema', 'json schema generator', 'sql table from json', 'online json sql tool'],
  },
  {
    id: 'datetime-hub',
    name: 'DateTime Hub',
    description: 'Advanced timezone and date calculator',
    category: 'math',
    icon: 'Clock',
    path: '/tools/datetime-hub',
    tags: ['date', 'time', 'timezone', 'calculator', 'timezone calculator', 'date calculator', 'time converter', 'online datetime tool'],
  },
  {
    id: 'js-logger',
    name: 'JS Console Prettifier',
    description: 'Visual debugger for complex JS objects',
    category: 'developer',
    icon: 'Bug',
    path: '/tools/js-logger',
    tags: ['js', 'console', 'debug', 'log', 'js console prettifier', 'javascript object viewer', 'js object inspector', 'online js debug tool'],
  },
  {
    id: 'og-debugger',
    name: 'Open Graph Debugger',
    description: 'Social media link preview simulator',
    category: 'developer',
    icon: 'Share2',
    path: '/tools/og-debugger',
    tags: ['og', 'seo', 'social', 'preview', 'open graph debugger', 'og tag checker', 'social media preview', 'link preview checker', 'facebook debugger'],
  },
  {
    id: 'html-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML code to Markdown syntax',
    category: 'text',
    icon: 'FileText',
    path: '/tools/html-markdown',
    tags: ['html', 'markdown', 'convert', 'content', 'html to markdown', 'html to md', 'html markdown converter', 'online html markdown'],
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate signed JSON Web Tokens',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/jwt-generator',
    tags: ['jwt', 'token', 'auth', 'generate', 'jwt generator', 'jwt token generator', 'json web token generator', 'online jwt tool'],
  },
  {
    id: 'gql-json',
    name: 'GraphQL to JSON',
    description: 'Generate mock JSON from GQL queries',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/gql-json',
    tags: ['graphql', 'json', 'mock', 'api', 'graphql to json', 'graphql mock generator', 'gql to json', 'online graphql tool'],
  },
  {
    id: 'mime-types',
    name: 'MIME Types',
    description: 'Lookup MIME types and file extensions',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/mime-types',
    tags: ['mime', 'file', 'type', 'extension', 'mime type lookup', 'file extension lookup', 'mime types list', 'online mime tool'],
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    description: 'Millisecond timer with lap tracking',
    category: 'math',
    icon: 'Timer',
    path: '/tools/stopwatch',
    tags: ['timer', 'stopwatch', 'chronometer', 'time', 'online stopwatch', 'free stopwatch', 'lap timer', 'millisecond timer'],
  },
  {
    id: 'numeronym',
    name: 'Numeronym Generator',
    description: 'Generate abbreviations like a11y, i18n',
    category: 'text',
    icon: 'Hash',
    path: '/tools/numeronym',
    tags: ['numeronym', 'abbreviation', 'a11y', 'i18n', 'numeronym generator', 'a11y abbreviation', 'i18n abbreviation', 'online numeronym tool'],
  },
  {
    id: 'nato-alphabet',
    name: 'Text to NATO',
    description: 'Convert text to NATO phonetic alphabet',
    category: 'text',
    icon: 'Globe',
    path: '/tools/nato-alphabet',
    tags: ['nato', 'phonetic', 'alphabet', 'spell', 'nato phonetic alphabet', 'phonetic alphabet converter', 'nato converter', 'online nato tool'],
  },
  {
    id: 'iban-validator',
    name: 'IBAN Validator',
    description: 'Validate IBAN bank account numbers instantly — checks the mod-97 checksum and country format, then shows the country, bank code and account number. Supports all SEPA and IBAN-registry countries.',
    category: 'converter',
    icon: 'Landmark',
    path: '/tools/iban-validator',
    tags: ['iban validator', 'iban checker', 'iban verification', 'bic swift', 'bank account validator', 'sepa', 'international bank transfer', 'iban', 'bank', 'validate', 'account number'],
  },
  {
    id: 'camera-recorder',
    name: 'Camera Recorder',
    description: 'Record video from camera or screen',
    category: 'image',
    icon: 'Camera',
    path: '/tools/camera-recorder',
    tags: ['video', 'record', 'camera', 'screen', 'camera recorder', 'screen recorder', 'webcam recorder', 'online video recorder'],
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'Browse and copy emojis easily',
    category: 'generator',
    icon: 'Smile',
    path: '/tools/emoji-picker',
    tags: ['emoji', 'smile', 'copy', 'social', 'emoji picker', 'copy emoji', 'emoji browser', 'online emoji tool'],
  },
  {
    id: 'ipv6-ula',
    name: 'IPv6 ULA Generator',
    description: 'Generate unique local IPv6 prefixes',
    category: 'developer',
    icon: 'Globe',
    path: '/tools/ipv6-ula',
    tags: ['ipv6', 'ula', 'network', 'rfc4193', 'ipv6 ula generator', 'unique local ipv6', 'ipv6 prefix generator', 'online ipv6 tool'],
  },
  {
    id: 'wysiwyg-editor',
    name: 'WYSIWYG Editor',
    description: 'Visual HTML editor with live source',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/wysiwyg-editor',
    tags: ['html', 'editor', 'wysiwyg', 'web', 'wysiwyg html editor', 'visual html editor', 'online html editor', 'html editor free'],
  },
  {
    id: 'phone-parser',
    name: 'Phone Parser',
    description: 'Validate and format phone numbers',
    category: 'text',
    icon: 'Phone',
    path: '/tools/phone-parser',
    tags: ['phone', 'format', 'validate', 'mobile', 'phone number validator', 'phone parser', 'validate phone number', 'online phone tool'],
  },
  {
    id: 'mac-address',
    name: 'MAC Address Tool',
    description: 'Generate and lookup MAC addresses',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/mac-address',
    tags: ['mac', 'address', 'oui', 'vendor', 'mac address lookup', 'mac address generator', 'oui lookup', 'online mac tool'],
  },
  {
    id: 'port-generator',
    name: 'Random Port Generator',
    description: 'Generate random non-conflicting ports',
    category: 'developer',
    icon: 'Server',
    path: '/tools/port-generator',
    tags: ['port', 'tcp', 'udp', 'network', 'random port generator', 'free port finder', 'tcp port generator', 'online port tool'],
  },
  {
    id: 'ip-range-expander',
    name: 'IP Range Expander',
    description: 'Expand CIDR and IP ranges to lists',
    category: 'developer',
    icon: 'Maximize2',
    path: '/tools/ip-range-expander',
    tags: ['ip', 'range', 'cidr', 'expand', 'ip range expander', 'cidr expander', 'ip list generator', 'online ip tool'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Minify and optimize SVG vector files',
    category: 'image',
    icon: 'Minimize2',
    path: '/tools/svg-optimizer',
    tags: ['svg', 'minify', 'optimize', 'vector', 'svg optimizer online', 'svg compressor', 'online svg optimizer', 'svg minifier', 'svg cleanup'],
  },
  {
    id: 'base64-image-to-file',
    name: 'Base64 to Image',
    description: 'Convert Base64 back to image files',
    category: 'converter',
    icon: 'FileImage',
    path: '/tools/base64-image-to-file',
    tags: ['base64', 'image', 'convert', 'decode', 'base64 to image', 'base64 to file', 'base64 decoder', 'online base64 tool'],
  },
  {
    id: 'text-compressor',
    name: 'Text Compressor',
    description: 'Test Gzip and Zlib text compression',
    category: 'developer',
    icon: 'Gauge',
    path: '/tools/text-compressor',
    tags: ['compress', 'gzip', 'zlib', 'size', 'text compression', 'gzip compressor', 'zlib compressor', 'online compression tool'],
  },
  {
    id: 'pdf-integrity',
    name: 'PDF Integrity Check',
    description: 'Verify PDF signatures and metadata',
    category: 'security',
    icon: 'FileSignature',
    path: '/tools/pdf-integrity',
    tags: ['pdf', 'signature', 'security', 'metadata', 'pdf integrity check', 'verify pdf signature', 'pdf metadata checker', 'online pdf security'],
  },
  {
    id: 'sql-json',
    name: 'SQL to JSON',
    description: 'Convert SQL INSERT to JSON array',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql-json',
    tags: ['sql', 'json', 'convert', 'data', 'sql to json', 'sql insert to json', 'database to json', 'online sql json tool'],
  },
  {
    id: 'curl-converter',
    name: 'Curl to Code',
    description: 'Convert curl commands to JS, Python, Go',
    category: 'developer',
    icon: 'Terminal',
    path: '/tools/curl-converter',
    tags: ['curl', 'fetch', 'api', 'convert', 'curl to code', 'curl converter', 'curl to javascript', 'curl to python', 'online curl tool'],
  },
  {
    id: 'json-sql',
    name: 'JSON to SQL',
    description: 'Generate SQL INSERT from JSON data',
    category: 'developer',
    icon: 'FileJson',
    path: '/tools/json-sql',
    tags: ['json', 'sql', 'convert', 'insert', 'json to sql', 'json to insert', 'json database converter', 'online json sql tool'],
  },
  {
    id: 'ssl-decoder',
    name: 'SSL Decoder',
    description: 'Decode and inspect X.509 certificates',
    category: 'security',
    icon: 'Lock',
    path: '/tools/ssl-decoder',
    tags: ['ssl', 'cert', 'x509', 'security', 'ssl decoder', 'certificate decoder', 'x509 decoder', 'ssl certificate parser', 'online ssl tool'],
  },
  {
    id: 'readability-analyzer',
    name: 'Readability Analyzer',
    description: 'Analyze text difficulty and grading',
    category: 'text',
    icon: 'BookOpen',
    path: '/tools/readability-analyzer',
    tags: ['text', 'readability', 'grading', 'flesch', 'readability analyzer', 'flesch reading ease', 'text difficulty checker', 'online readability tool'],
  },
  {
    id: 'css-grid',
    name: 'CSS Grid Generator',
    description: 'Design complex grid layouts visually',
    category: 'image',
    icon: 'LayoutGrid',
    path: '/tools/css-grid',
    tags: ['css', 'grid', 'layout', 'design', 'css grid generator', 'grid layout generator', 'css grid tool', 'grid maker'],
  },
  {
    id: 'css-flexbox',
    name: 'CSS Flexbox Generator',
    description: 'Build flexible flexbox containers visually',
    category: 'image',
    icon: 'Layout',
    path: '/tools/css-flexbox',
    tags: ['css', 'flexbox', 'layout', 'design', 'flexbox generator', 'css flexbox generator', 'flex layout generator', 'css layout tool'],
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check WCAG color contrast accessibility',
    category: 'image',
    icon: 'Palette',
    path: '/tools/contrast-checker',
    tags: ['accessibility', 'color', 'contrast', 'wcag', 'contrast checker', 'color contrast checker', 'wcag contrast checker', 'accessibility checker', 'a11y contrast'],
  },
  {
    id: 'json5-converter',
    name: 'JSON5 to JSON',
    description: 'Convert JSON5 to standard JSON',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json5-converter',
    tags: ['json', 'json5', 'convert', 'strict', 'json5 to json', 'json5 converter', 'json5 parser', 'online json5 tool'],
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and preview aspect ratios',
    category: 'image',
    icon: 'Maximize2',
    path: '/tools/aspect-ratio',
    tags: ['design', 'image', 'aspect', 'ratio', 'aspect ratio calculator', 'image ratio', 'screen ratio calculator', 'online aspect ratio tool'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette Extractor',
    description: 'Extract color schemes from any image',
    category: 'image',
    icon: 'Palette',
    path: '/tools/color-palette',
    tags: ['color', 'palette', 'image', 'extract', 'color palette extractor', 'palette generator from image', 'image color picker', 'dominant colors extractor'],
  },
  {
    id: 'lottie-preview',
    name: 'Lottie Previewer',
    description: 'Test and inspect Lottie JSON animations',
    category: 'image',
    icon: 'Play',
    path: '/tools/lottie-preview',
    tags: ['lottie', 'animation', 'json', 'visual', 'lottie previewer', 'lottie viewer online', 'lottie animation tester', 'online lottie tool'],
  },
  {
    id: 'json-go',
    name: 'JSON to Go Struct',
    description: 'Convert JSON to Go data structures',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/json-go',
    tags: ['json', 'go', 'golang', 'struct', 'json to go', 'json to golang struct', 'go struct generator', 'online json go tool'],
  },
  {
    id: 'performance-benchmark',
    name: 'Performance Benchmark',
    description: 'Compare JS code snippet speeds',
    category: 'developer',
    icon: 'Activity',
    path: '/tools/performance-benchmark',
    tags: ['benchmark', 'performance', 'js', 'speed', 'js benchmark', 'javascript performance test', 'code speed comparison', 'online js benchmark'],
  },
  {
    id: 'cron-validator',
    name: 'Cron Validator',
    description: 'Verify and test cron expressions',
    category: 'developer',
    icon: 'ShieldCheck',
    path: '/tools/cron-validator',
    tags: ['cron', 'validate', 'schedule', 'test', 'cron validator', 'cron expression validator', 'crontab checker', 'online cron validator'],
  },
  {
    id: 'svg-path',
    name: 'SVG Path Visualizer',
    description: 'Visual playground for SVG path data',
    category: 'image',
    icon: 'PenTool',
    path: '/tools/svg-path',
    tags: ['svg', 'path', 'draw', 'vector', 'svg path visualizer', 'svg path editor', 'svg path generator', 'online svg path tool'],
  },
  {
    id: 'box-shadow',
    name: 'Box Shadow Studio',
    description: 'Design modern multi-layered CSS shadows',
    category: 'image',
    icon: 'Layers',
    path: '/tools/box-shadow',
    tags: ['css', 'shadow', 'design', 'ui', 'css box shadow generator', 'box shadow generator', 'css shadow maker', 'drop shadow generator'],
  },
  {
    id: 'gradient-studio',
    name: 'Gradient Studio',
    description: 'Build complex linear and radial gradients',
    category: 'image',
    icon: 'Palette',
    path: '/tools/gradient-studio',
    tags: ['css', 'gradient', 'design', 'ui', 'css gradient generator', 'linear gradient generator', 'radial gradient generator', 'gradient maker', 'css background gradient'],
  },
  {
    id: 'md-table-generator',
    name: 'Markdown Table Generator',
    description: 'Visually build Markdown tables',
    category: 'text',
    icon: 'Table',
    path: '/tools/md-table-generator',
    tags: ['markdown', 'table', 'documentation', 'generator', 'markdown table generator', 'md table maker', 'markdown table creator', 'online markdown table'],
  },
  {
    id: 'cron-tester',
    name: 'Cron Expression Tester',
    description: 'Test cron expressions and preview the next scheduled execution dates with timezone support',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/cron-tester',
    tags: ['cron', 'tester', 'schedule', 'predict', 'crontab', 'job scheduler', 'linux', 'next run', 'cron expression tester', 'online cron tester', 'crontab validator', 'cron schedule checker'],
  },
  {
    id: 'json-schema',
    name: 'JSON Schema Generator',
    description: 'Generate JSON Schema from JSON data',
    category: 'developer',
    icon: 'Database',
    path: '/tools/json-schema',
    tags: ['json', 'schema', 'api', 'generate', 'json schema generator', 'json to schema', 'online json schema', 'json schema maker'],
  },
  {
    id: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, Kelvin',
    category: 'converter',
    icon: 'Thermometer',
    path: '/tools/temperature-converter',
    tags: ['temperature', 'celsius', 'fahrenheit', 'convert', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin converter', 'temperature conversion tool'],
  },
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    description: 'Interactive collapsible JSON tree viewer',
    category: 'developer',
    icon: 'FileJson',
    path: '/tools/json-viewer',
    tags: ['json', 'tree', 'viewer', 'visualize', 'json viewer online', 'json tree viewer', 'json explorer', 'json inspector', 'online json viewer'],
  },
  {
    id: 'text-statistics',
    name: 'Text Statistics',
    description: 'Detailed analysis of text structure',
    category: 'text',
    icon: 'BarChart3',
    path: '/tools/text-statistics',
    tags: ['text', 'stats', 'analysis', 'insights', 'text statistics', 'text analyzer', 'text analysis tool', 'online text stats'],
  },
  {
    id: 'json-ts',
    name: 'JSON to TypeScript',
    description: 'Generate TS interfaces from JSON',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/json-ts',
    tags: ['json', 'typescript', 'interface', 'generate', 'json to typescript', 'json to ts', 'typescript interface generator', 'online json ts tool'],
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism Studio',
    description: 'Generate CSS frosted glass effects',
    category: 'image',
    icon: 'Layers',
    path: '/tools/glassmorphism',
    tags: ['css', 'glass', 'ui', 'design', 'glassmorphism generator', 'frosted glass css', 'glass effect css', 'glassmorphism css generator'],
  },
  {
    id: 'svg-jsx',
    name: 'SVG to JSX',
    description: 'Convert SVG to React components',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/svg-jsx',
    tags: ['svg', 'jsx', 'react', 'convert', 'svg to jsx', 'svg to react', 'svg react component', 'online svg jsx tool'],
  },
  {
    id: 'color-blindness',
    name: 'Color Blindness Simulator',
    description: 'Test UI accessibility for color vision',
    category: 'image',
    icon: 'Eye',
    path: '/tools/color-blindness',
    tags: ['accessibility', 'color', 'vision', 'test', 'color blindness simulator', 'color vision test', 'a11y color test', 'online color blindness tool'],
  },
  {
    id: 'ipv4-address-converter',
    name: 'IPv4 Address Converter',
    description: 'Convert IPv4 addresses to integer, binary, hexadecimal, and CIDR notation — essential for network programming and subnet calculations',
    category: 'converter',
    icon: 'Network',
    path: '/tools/ipv4-address-converter',
    tags: ['ip converter', 'ipv4 converter', 'ip to binary', 'ip to decimal', 'ip to hex', 'network tools', 'subnet', 'cidr', 'ipv4', 'ip address', 'convert'],
  },
  {
    id: 'toml-yaml',
    name: 'TOML ↔ YAML',
    description: 'Convert between TOML and YAML formats',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/toml-yaml',
    tags: ['toml', 'yaml', 'convert', 'config', 'toml to yaml', 'yaml to toml', 'toml yaml converter', 'online toml yaml tool'],
  },
  {
    id: 'yaml-viewer',
    name: 'YAML Viewer & Formatter',
    description: 'Beautify and sort YAML data',
    category: 'developer',
    icon: 'Eye',
    path: '/tools/yaml-viewer',
    tags: ['yaml', 'format', 'beautify', 'viewer', 'yaml formatter online', 'yaml viewer', 'yaml beautifier', 'online yaml tool'],
  },
  {
    id: 'git-memo',
    name: 'Git Cheat Sheet',
    description: 'Commonly used Git commands reference',
    category: 'developer',
    icon: 'GitBranch',
    path: '/tools/git-memo',
    tags: ['git', 'cheat', 'sheet', 'reference', 'git cheat sheet', 'git commands reference', 'git quick reference', 'online git guide'],
  },
  {
    id: 'regex-memo',
    name: 'Regex Cheat Sheet',
    description: 'Regular expression syntax reference',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex-memo',
    tags: ['regex', 'cheat', 'sheet', 'reference', 'regex cheat sheet', 'regular expression reference', 'regex syntax guide', 'online regex guide'],
  },
  {
    id: 'email-normalizer',
    name: 'Email Normalizer',
    description: 'Clean and normalize email addresses',
    category: 'developer',
    icon: 'Mail',
    path: '/tools/email-normalizer',
    tags: ['email', 'clean', 'normalize', 'gmail', 'email normalizer', 'email cleaner', 'normalize email address', 'online email tool'],
  },
  {
    id: 'eta-calculator',
    name: 'ETA Calculator',
    description: 'Calculate estimated time of arrival',
    category: 'math',
    icon: 'Clock',
    path: '/tools/eta-calculator',
    tags: ['eta', 'time', 'progress', 'calculate', 'eta calculator', 'estimated time arrival', 'arrival time calculator', 'online eta tool'],
  },
  {
    id: 'math-evaluator',
    name: 'Math Evaluator',
    description: 'Evaluate complex math expressions',
    category: 'math',
    icon: 'Sigma',
    path: '/tools/math-evaluator',
    tags: ['math', 'eval', 'expression', 'scientific', 'math evaluator online', 'expression calculator', 'scientific calculator online', 'complex math solver'],
  },
  {
    id: 'string-obfuscator',
    name: 'String Obfuscator',
    description: 'Mask sensitive parts of a string',
    category: 'security',
    icon: 'ShieldEllipsis',
    path: '/tools/string-obfuscator',
    tags: ['mask', 'obfuscate', 'security', 'privacy', 'string obfuscator', 'text masker', 'data masking', 'online obfuscation tool'],
  },
  {
    id: 'text-unicode',
    name: 'Text to Unicode',
    description: 'Convert text to Unicode escape sequences',
    category: 'converter',
    icon: 'Code',
    path: '/tools/text-unicode',
    tags: ['unicode', 'hex', 'escape', 'convert', 'text to unicode', 'unicode converter', 'unicode escape online', 'text to unicode escape'],
  },
  {
    id: 'wifi-qr',
    name: 'WiFi QR Generator',
    description: 'Create QR codes for WiFi networks',
    category: 'generator',
    icon: 'Wifi',
    path: '/tools/wifi-qr',
    tags: ['wifi', 'qr', 'network', 'connect', 'wifi qr code', 'wifi qr generator', 'share wifi qr', 'wifi password qr', 'online wifi qr'],
  },
  {
    id: 'json-minify',
    name: 'JSON Minifier',
    description: 'Compress JSON by removing whitespace',
    category: 'developer',
    icon: 'Minimize2',
    path: '/tools/json-minify',
    tags: ['json', 'minify', 'compress', 'optimize', 'json minifier online', 'json compressor', 'compact json', 'online json minify tool'],
  },
  {
    id: 'text-binary',
    name: 'Text ↔ Binary',
    description: 'Convert text to binary and vice versa',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/text-binary',
    tags: ['text', 'binary', 'convert', 'encode', 'text to binary', 'binary to text', 'binary converter', 'online binary tool'],
  },
  {
    id: 'safelink-decoder',
    name: 'Safelink Decoder',
    description: 'Decode Outlook / Office 365 safelinks',
    category: 'security',
    icon: 'Unlock',
    path: '/tools/safelink-decoder',
    tags: ['safelink', 'outlook', 'decode', 'security', 'safelink decoder', 'outlook safelink', 'office 365 safelink', 'online safelink tool'],
  },
  {
    id: 'svg-placeholder',
    name: 'SVG Placeholder',
    description: 'Generate custom SVG placeholder images',
    category: 'image',
    icon: 'Image',
    path: '/tools/svg-placeholder',
    tags: ['svg', 'placeholder', 'image', 'design', 'svg placeholder generator', 'placeholder image generator', 'svg mockup', 'online svg placeholder'],
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate message authentication codes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hmac-generator',
    tags: ['hmac', 'security', 'auth', 'hash', 'hmac generator', 'hmac sha256', 'online hmac tool', 'message authentication code'],
  },
  {
    id: 'otp-generator',
    name: 'OTP Generator',
    description: 'Generate 2FA TOTP authentication codes',
    category: 'security',
    icon: 'Clock',
    path: '/tools/otp-generator',
    tags: ['otp', 'totp', '2fa', 'security', 'totp generator', 'otp code generator', '2fa code generator', 'online totp tool'],
  },
  {
    id: 'bip39',
    name: 'BIP39 Generator',
    description: 'Generate secure mnemonic seed phrases',
    category: 'security',
    icon: 'Coins',
    path: '/tools/bip39',
    tags: ['mnemonic', 'seed', 'crypto', 'bitcoin', 'bip39 generator', 'seed phrase generator', 'crypto mnemonic', 'online bip39 tool'],
  },
  {
    id: 'device-info',
    name: 'Device Information',
    description: 'View hardware and browser details',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/device-info',
    tags: ['device', 'browser', 'hardware', 'specs', 'device info', 'browser info', 'system information', 'online device checker'],
  },
  {
    id: 'keycode-info',
    name: 'Keycode Info',
    description: 'Find keyboard event keycodes and info',
    category: 'developer',
    icon: 'Keyboard',
    path: '/tools/keycode-info',
    tags: ['keycode', 'keyboard', 'event', 'js', 'keycode lookup', 'javascript keycode', 'keyboard event codes', 'online keycode tool'],
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO and social media meta tags',
    category: 'developer',
    icon: 'Share2',
    path: '/tools/meta-tag-generator',
    tags: ['seo', 'meta', 'og', 'twitter', 'social', 'meta tag generator', 'seo meta tags', 'open graph generator', 'online meta tag tool'],
  },
  {
    id: 'json-toml',
    name: 'JSON ↔ TOML',
    description: 'Convert between JSON and TOML formats',
    category: 'developer',
    icon: 'FileTerminal',
    path: '/tools/json-toml',
    tags: ['json', 'toml', 'convert', 'config', 'json to toml', 'toml to json', 'json toml converter', 'online json toml tool'],
  },
  {
    id: 'json-xml',
    name: 'JSON ↔ XML',
    description: 'Convert between JSON and XML formats',
    category: 'developer',
    icon: 'Code',
    path: '/tools/json-xml',
    tags: ['json', 'xml', 'convert', 'data', 'json to xml', 'xml to json', 'json xml converter', 'online json xml tool'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and beautify XML data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/xml-formatter',
    tags: ['xml', 'format', 'beautify', 'pretty', 'xml formatter online', 'xml beautifier', 'xml pretty print', 'online xml tool'],
  },
  {
    id: 'ulid-generator',
    name: 'ULID Generator',
    description: 'Generate sortable unique identifiers',
    category: 'generator',
    icon: 'ArrowDown01',
    path: '/tools/ulid-generator',
    tags: ['ulid', 'id', 'unique', 'sortable', 'ulid generator', 'sortable id generator', 'unique id generator', 'online ulid tool'],
  },
  {
    id: 'integer-base-converter',
    name: 'Integer Base Converter',
    description: 'Convert numbers between decimal, hexadecimal, binary, and octal — instantly with a step-by-step breakdown',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/integer-base-converter',
    tags: ['binary converter', 'hex converter', 'decimal to binary', 'decimal to hex', 'base conversion', 'number system converter', 'octal', 'programmer calculator', 'binary', 'hex', 'decimal', 'convert'],
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert Arabic numbers to Roman numerals',
    category: 'converter',
    icon: 'History',
    path: '/tools/roman-numeral-converter',
    tags: ['roman', 'numeral', 'math', 'convert', 'roman numeral converter', 'roman to arabic', 'arabic to roman', 'online roman numeral'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare and find differences in JSON',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-diff',
    tags: ['json', 'diff', 'compare', 'structural', 'json diff online', 'compare json', 'json comparator', 'json difference finder'],
  },
  {
    id: 'token-generator',
    name: 'Secure Token Generator',
    description: 'Generate secure random API tokens',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/token-generator',
    tags: ['token', 'secret', 'key', 'generate', 'token generator', 'api token generator', 'secure token generator', 'random token generator'],
  },
  {
    id: 'rsa-generator',
    name: 'RSA Key Generator',
    description: 'Generate RSA public and private keys',
    category: 'security',
    icon: 'Key',
    path: '/tools/rsa-generator',
    tags: ['rsa', 'key', 'generator', 'security', 'rsa key generator', 'rsa key pair generator', 'public private key generator', 'online rsa tool'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength',
    description: 'Analyze password security and crack time',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/password-strength',
    tags: ['password', 'strength', 'security', 'analyze', 'password strength checker', 'password security checker', 'password crack time', 'password analyzer', 'online password checker'],
  },
  {
    id: 'base64-file',
    name: 'Base64 File Converter',
    description: 'Convert images and files to Base64 strings',
    category: 'converter',
    icon: 'FileUp',
    path: '/tools/base64-file',
    tags: ['base64', 'file', 'image', 'convert', 'base64 file converter', 'file to base64', 'image to base64', 'online base64 tool'],
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Codes',
    description: 'Complete reference for HTTP response codes',
    category: 'developer',
    icon: 'BookOpen',
    path: '/tools/http-status-codes',
    tags: ['http', 'status', 'code', 'reference', 'http status codes', 'http response codes', 'http code reference', 'online http status guide'],
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV',
    description: 'Convert between JSON arrays and CSV',
    category: 'developer',
    icon: 'FileSpreadsheet',
    path: '/tools/json-csv',
    tags: ['json', 'csv', 'convert', 'spreadsheet', 'json to csv', 'csv to json', 'json csv converter', 'online json csv tool'],
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Break down complex URLs into parts',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-parser',
    tags: ['url', 'parse', 'query', 'params', 'url parser online', 'url breakdown', 'url query parser', 'online url tool'],
  },
  {
    id: 'markdown-html',
    name: 'Markdown ↔ HTML',
    description: 'Convert and preview Markdown and HTML',
    category: 'text',
    icon: 'FileText',
    path: '/tools/markdown-html',
    tags: ['markdown', 'html', 'convert', 'preview', 'markdown to html', 'html to markdown', 'markdown converter', 'online markdown tool'],
  },
  {
    id: 'basic-auth',
    name: 'Basic Auth Generator',
    description: 'Generate HTTP Basic Auth headers',
    category: 'security',
    icon: 'Lock',
    path: '/tools/basic-auth',
    tags: ['auth', 'basic', 'header', 'security', 'basic auth generator', 'http basic auth', 'basic authentication', 'online auth tool'],
  },
  {
    id: 'aes-encryption',
    name: 'AES Encryption',
    description: 'Encrypt and decrypt text with AES',
    category: 'security',
    icon: 'Lock',
    path: '/tools/aes-encryption',
    tags: ['aes', 'encryption', 'decryption', 'security', 'aes encrypt online', 'aes decrypt online', 'aes 256 encryption', 'online encryption tool'],
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt Hash/Verify',
    description: 'Hash and verify passwords with Bcrypt',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/bcrypt',
    tags: ['bcrypt', 'password', 'hash', 'security', 'bcrypt hash generator', 'bcrypt online', 'bcrypt password hash', 'online bcrypt tool'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex-tester',
    tags: ['regex', 'test', 'debug', 'developer', 'regex tester online', 'online regex tester', 'regex checker', 'regex validator', 'regular expression tester'],
  },
  {
    id: 'ascii-text-drawer',
    name: 'ASCII Text Drawer',
    description: 'Generate ASCII art banners and text',
    category: 'generator',
    icon: 'Layout',
    path: '/tools/ascii-text-drawer',
    tags: ['ascii', 'art', 'banner', 'generate', 'ascii art generator', 'ascii text generator', 'banner generator', 'online ascii art'],
  },
  {
    id: 'hash-text',
    name: 'Hash Text',
    description: 'Generate MD5, SHA1, SHA256 hashes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hash-text',
    tags: ['hash', 'md5', 'sha256', 'security', 'hash generator online', 'md5 hash generator', 'sha256 hash generator', 'sha1 hash generator', 'online hash tool', 'text hash'],
  },
  {
    id: 'crontab-generator',
    name: 'Crontab Generator',
    description: 'Create and understand cron expressions',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/crontab-generator',
    tags: ['cron', 'crontab', 'schedule', 'linux', 'crontab generator', 'cron expression generator', 'cron maker', 'online cron tool'],
  },
  {
    id: 'docker-compose-converter',
    name: 'Docker Run to Compose',
    description: 'Convert docker run to docker-compose.yml',
    category: 'developer',
    icon: 'Box',
    path: '/tools/docker-compose-converter',
    tags: ['docker', 'compose', 'devops', 'convert', 'docker run to compose', 'docker compose converter', 'docker compose generator', 'online docker tool'],
  },
  {
    id: 'list-converter',
    name: 'List Converter',
    description: 'Sort, deduplicate, and clean up text lists',
    category: 'text',
    icon: 'ListOrdered',
    path: '/tools/list-converter',
    tags: ['list', 'sort', 'unique', 'clean', 'list converter', 'sort list online', 'deduplicate list', 'online list tool'],
  },
  {
    id: 'slugify',
    name: 'Slugify String',
    description: 'Convert text to URL-friendly slugs',
    category: 'text',
    icon: 'Link2',
    path: '/tools/slugify',
    tags: ['slug', 'url', 'seo', 'convert', 'slugify', 'url slug generator', 'text to slug', 'online slugify tool'],
  },
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    description: 'Calculate IPv4 subnets and CIDR masks',
    category: 'developer',
    icon: 'Network',
    path: '/tools/subnet-calculator',
    tags: ['ip', 'subnet', 'network', 'cidr', 'subnet calculator', 'cidr calculator', 'ip subnet calculator', 'network calculator', 'online subnet tool'],
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Decode browser user agent strings',
    category: 'developer',
    icon: 'Search',
    path: '/tools/user-agent-parser',
    tags: ['ua', 'useragent', 'browser', 'device', 'user agent parser', 'browser detector', 'useragent string parser', 'online ua tool'],
  },
  {
    id: 'sql-prettify',
    name: 'SQL Prettify',
    description: 'Format and beautify your SQL queries',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql-prettify',
    tags: ['sql', 'format', 'beautify', 'db', 'sql formatter online', 'sql beautifier', 'sql pretty printer', 'online sql tool'],
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Linux file permissions',
    category: 'developer',
    icon: 'Shield',
    path: '/tools/chmod-calculator',
    tags: ['chmod', 'linux', 'permission', 'security', 'chmod calculator', 'linux permissions', 'chmod generator', 'online chmod tool'],
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'Convert data between JSON and YAML formats',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-yaml',
    tags: ['json', 'yaml', 'convert', 'json to yaml', 'yaml to json', 'json yaml converter', 'online json yaml tool'],
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    description: 'Decode and analyze JSON Web Tokens',
    category: 'developer',
    icon: 'Fingerprint',
    path: '/tools/jwt-parser',
    tags: ['jwt', 'json', 'token', 'decode', 'jwt decoder', 'jwt token decoder', 'jwt analyzer', 'online jwt tool', 'json web token'],
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    description: 'Encode and decode HTML entities',
    category: 'developer',
    icon: 'Code',
    path: '/tools/html-entities',
    tags: ['html', 'entities', 'encode', 'decode', 'html entity encoder', 'html entity decoder', 'html escape', 'html unescape', 'online html tool'],
  },
  {
    id: 'html-tag-stripper',
    name: 'HTML Tag Stripper',
    description: 'Remove HTML tags and extract plain text',
    category: 'developer',
    icon: 'Eraser',
    path: '/tools/html-tag-stripper',
    tags: ['html', 'strip', 'tags', 'text', 'html tag stripper', 'remove html tags', 'plain text extractor', 'online html stripper'],
  },
  {
    id: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort text lines alphabetically or numerically',
    category: 'text',
    icon: 'ArrowDownAZ',
    path: '/tools/text-sorter',
    tags: ['text', 'sort', 'alphabetical', 'list', 'text sorter', 'sort lines', 'alphabetical sorter', 'online text sort'],
  },
  {
    id: 'text-cleaner',
    name: 'Text Cleaner',
    description: 'Clean up messy text by removing extra spaces and formatting',
    category: 'text',
    icon: 'Eraser',
    path: '/tools/text-cleaner',
    tags: ['text', 'clean', 'format', 'whitespace', 'text cleaner', 'remove extra spaces', 'clean text online', 'online text cleaner'],
  },
  {
    id: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat any text multiple times with custom separators',
    category: 'text',
    icon: 'Repeat',
    path: '/tools/text-repeater',
    tags: ['text', 'repeat', 'duplicate', 'string', 'text repeater', 'repeat text', 'string repeater', 'online text repeater'],
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse text, words, or lines instantly',
    category: 'text',
    icon: 'ArrowLeftRight',
    path: '/tools/text-reverser',
    tags: ['text', 'reverse', 'flip', 'mirror', 'text reverser', 'reverse words', 'reverse lines', 'online text reverser'],
  },
  {
    id: 'line-numbers',
    name: 'Line Numbers',
    description: 'Add or remove sequential line numbering',
    category: 'text',
    icon: 'ListOrdered',
    path: '/tools/line-numbers',
    tags: ['text', 'lines', 'numbers', 'format', 'line numbers', 'add line numbers', 'remove line numbers', 'online line numbering'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder text for designs',
    category: 'generator',
    icon: 'FileText',
    path: '/tools/lorem-ipsum',
    tags: ['lorem', 'ipsum', 'text', 'generate', 'lorem ipsum generator', 'placeholder text generator', 'dummy text generator', 'online lorem ipsum'],
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and beautify JSON data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-formatter',
    tags: ['json', 'format', 'beautify', 'json formatter online', 'json beautifier', 'json validator', 'pretty print json', 'json prettifier'],
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings',
    category: 'developer',
    icon: 'Lock',
    path: '/tools/base64-encoder',
    tags: ['base64', 'encode', 'decode', 'base64 encoder online', 'base64 decoder', 'base64 converter', 'online base64 tool'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL strings',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-encoder',
    tags: ['url', 'encode', 'decode', 'url encoder', 'url decoder', 'percent encoding', 'online url tool'],
  },
  
  // Text Tools
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and lines',
    category: 'text',
    icon: 'Hash',
    path: '/tools/word-counter',
    tags: ['text', 'count', 'words', 'word counter online', 'character counter', 'line counter', 'text statistics', 'online word count tool'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different cases',
    category: 'text',
    icon: 'Type',
    path: '/tools/case-converter',
    tags: ['text', 'case', 'convert', 'case converter', 'uppercase to lowercase', 'camelCase converter', 'snake_case converter', 'text case changer'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and find differences',
    category: 'text',
    icon: 'Diff',
    path: '/tools/text-diff',
    tags: ['text', 'diff', 'compare', 'text diff checker', 'compare text online', 'diff checker', 'text comparison tool', 'find differences'],
  },
  
  // Converters
  {
    id: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and back — supports milliseconds, seconds, ISO 8601, and any timezone. Live current timestamp included.',
    category: 'converter',
    icon: 'Clock',
    path: '/tools/timestamp-converter',
    tags: ['unix timestamp converter', 'epoch converter', 'timestamp to date', 'date to timestamp', 'unix time', 'epoch time', 'iso 8601', 'timezone converter', 'timestamp', 'unix', 'epoch', 'date', 'time'],
  },
  {
    id: 'iso-formatter',
    name: 'ISO 8601 Date Formatter',
    description: 'Format dates to standard ISO 8601 instantly for developers and databases',
    category: 'converter',
    icon: 'Calendar',
    path: '/tools/iso-formatter',
    tags: ['iso 8601', 'date formatter', 'iso date', 'timestamp formatter', 'iso format', 'date standard', 'developer date tool', 'online iso formatter'],
  },
  {
    id: 'morse-code-converter',
    name: 'Morse Code Converter',
    description: 'Convert text to Morse code and decode Morse code back to text instantly',
    category: 'converter',
    icon: 'Radio',
    path: '/tools/morse-code-converter',
    tags: ['morse code', 'morse translator', 'text to morse', 'morse to text', 'morse code converter', 'morse decoder', 'online morse code', 'radio signals'],
  },
  {
    id: 'time-duration-converter',
    name: 'Time Duration Converter',
    description: 'Easily convert between milliseconds, seconds, hours, days, and years instantly',
    category: 'converter',
    icon: 'Hourglass',
    path: '/tools/time-duration-converter',
    tags: ['time duration', 'time converter', 'seconds to minutes', 'hours to days', 'milliseconds converter', 'time calculator', 'duration converter', 'online time converter'],
  },
  {
    id: 'time-zone-converter',
    name: 'Global Timezone Converter',
    description: 'Easily sync times across different time zones with our real-time world clock',
    category: 'converter',
    icon: 'Globe',
    path: '/tools/time-zone-converter',
    tags: ['timezone', 'time zone converter', 'world clock', 'utc converter', 'dst calculator', 'global time', 'meeting planner', 'online timezone tool'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units',
    category: 'converter',
    icon: 'Ruler',
    path: '/tools/unit-converter',
    tags: ['unit', 'convert', 'measurement', 'unit converter online', 'measurement converter', 'online unit conversion', 'free unit converter'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between color formats',
    category: 'color',
    icon: 'Palette',
    path: '/tools/color-converter',
    tags: ['color', 'convert', 'hex', 'rgb', 'color converter online', 'hex to rgb', 'rgb to hex', 'color code converter', 'online color tool'],
  },
  
  // Math
  {
    id: 'calculator',
    name: 'Calculator',
    description: 'Simple and scientific calculator',
    category: 'math',
    icon: 'Calculator',
    path: '/tools/calculator',
    tags: ['math', 'calculator', 'calculate', 'online calculator', 'scientific calculator', 'free calculator', 'math calculator'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages easily',
    category: 'math',
    icon: 'Percent',
    path: '/tools/percentage-calculator',
    tags: ['math', 'percentage', 'calculate', 'percentage calculator', 'percent calculator', 'online percentage', 'percentage finder'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days',
    category: 'math',
    icon: 'Calendar',
    path: '/tools/age-calculator',
    tags: ['age', 'birthday', 'date', 'age calculator', 'how old am i', 'birthdate calculator', 'age in days', 'online age calculator'],
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index and understand your health status',
    category: 'math',
    icon: 'Scale',
    path: '/tools/bmi-calculator',
    tags: ['bmi', 'health', 'weight', 'body mass index', 'bmi calculator', 'calculate bmi', 'ideal weight', 'online bmi calculator'],
  },
  {
    id: 'calorie-calculator',
    name: 'Calorie Calculator',
    description: 'Estimate your daily calorie needs and macronutrient breakdown',
    category: 'math',
    icon: 'Flame',
    path: '/tools/calorie-calculator',
    tags: ['calorie', 'diet', 'nutrition', 'calorie calculator', 'daily calorie needs', 'calorie counter', 'macro calculator', 'online calorie calculator'],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate distance between dates or project future deadlines',
    category: 'math',
    icon: 'CalendarDays',
    path: '/tools/date-calculator',
    tags: ['date', 'time', 'deadline', 'date calculator', 'days between dates', 'date difference', 'future date', 'online date calculator'],
  },
  {
    id: 'fraction-calculator',
    name: 'Fraction Calculator',
    description: 'Perform arithmetic operations on fractions with simplified results',
    category: 'math',
    icon: 'Divide',
    path: '/tools/fraction-calculator',
    tags: ['fraction', 'math', 'arithmetic', 'fraction calculator', 'simplify fractions', 'fraction operations', 'add fractions', 'online fraction calculator'],
  },
  {
    id: 'gpa-calculator',
    name: 'GPA Calculator',
    description: 'Track your grades and see your weighted or unweighted GPA',
    category: 'math',
    icon: 'GraduationCap',
    path: '/tools/gpa-calculator',
    tags: ['gpa', 'grades', 'school', 'gpa calculator', 'calculate gpa', 'weighted gpa', 'college gpa', 'online gpa calculator'],
  },
  {
    id: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    description: 'Estimate your healthy weight range based on WHO standards',
    category: 'math',
    icon: 'Target',
    path: '/tools/ideal-weight-calculator',
    tags: ['weight', 'health', 'ideal weight', 'ideal weight calculator', 'healthy weight range', 'body weight', 'online ideal weight calculator'],
  },
  {
    id: 'salary-calculator',
    name: 'Salary Calculator',
    description: 'Calculate and convert your salary across different pay periods',
    category: 'math',
    icon: 'Banknote',
    path: '/tools/salary-calculator',
    tags: ['salary', 'income', 'wage', 'salary calculator', 'hourly to salary', 'pay calculator', 'annual salary', 'online salary calculator'],
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Split bills and calculate tips instantly for dining and services',
    category: 'math',
    icon: 'Receipt',
    path: '/tools/tip-calculator',
    tags: ['tip', 'bill', 'restaurant', 'tip calculator', 'split bill', 'gratuity calculator', 'dining tip', 'online tip calculator'],
  },
  {
    id: 'zakat-calculator',
    name: 'Zakat Calculator',
    description: 'Calculate your obligatory charity based on your current wealth',
    category: 'math',
    icon: 'Moon',
    path: '/tools/zakat-calculator',
    tags: ['zakat', 'charity', 'islam', 'zakat calculator', 'calculate zakat', 'nisab', 'islamic charity', 'online zakat calculator'],
  },

  // Generators
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    category: 'security',
    icon: 'Key',
    path: '/tools/password-generator',
    tags: ['password', 'generate', 'security', 'password generator', 'strong password generator', 'secure password generator', 'random password generator', 'online password generator'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/uuid-generator',
    tags: ['uuid', 'generate', 'random', 'uuid generator', 'online uuid generator', 'guid generator', 'uuid v4', 'uuid v7', 'unique id generator'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text',
    category: 'generator',
    icon: 'QrCode',
    path: '/tools/qr-generator',
    tags: ['qr', 'generate', 'code', 'qr code generator', 'free qr code generator', 'online qr code generator', 'qr code maker', 'qr creator'],
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers with custom ranges and options',
    category: 'generator',
    icon: 'Dices',
    path: '/tools/random-number-generator',
    tags: ['random number', 'number generator', 'random picker', 'lottery numbers', 'dice roller', 'random generator', 'online random number', 'number picker'],
  },
  {
    id: 'formal-email-generator',
    name: 'Formal Email Generator',
    description: 'Craft professional emails in seconds with ready-made templates',
    category: 'generator',
    icon: 'Mail',
    path: '/tools/formal-email-generator',
    tags: ['email generator', 'formal email', 'professional email', 'email template', 'business email', 'cover letter generator', 'online email tool'],
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices with custom items, tax, and totals',
    category: 'generator',
    icon: 'FileText',
    path: '/tools/invoice-generator',
    tags: ['invoice', 'invoice generator', 'pdf invoice', 'billing', 'freelance invoice', 'online invoice maker', 'invoice creator', 'business invoice'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic hashes from text or files with support for multiple SHA algorithms',
    category: 'developer',
    icon: 'Fingerprint',
    path: '/tools/hash-generator',
    tags: ['hash', 'sha', 'cryptography', 'sha-256', 'sha-512', 'hash generator', 'checksum', 'online hash tool', 'crypto hash'],
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Create custom barcodes in various industry-standard formats including CODE128, EAN-13, UPC and more',
    category: 'generator',
    icon: 'Barcode',
    path: '/tools/barcode-generator',
    tags: ['barcode', 'barcode generator', 'ean-13', 'upc', 'code128', 'qr barcode', 'online barcode maker', 'retail barcode'],
  },
  {
    id: 'faq-schema',
    name: 'FAQ Schema Generator',
    description: 'Create JSON-LD FAQ schema to get rich snippets in Google search results',
    category: 'seo',
    icon: 'HelpCircle',
    path: '/tools/faq-schema',
    tags: ['faq schema', 'json-ld', 'rich snippets', 'seo schema', 'structured data', 'google faq', 'schema generator'],
  },
  {
    id: 'keywords',
    name: 'Keywords Extractor & Analyzer',
    description: 'Extract important terms and analyze keyword density for content optimization',
    category: 'seo',
    icon: 'Search',
    path: '/tools/keywords',
    tags: ['keyword density', 'seo analysis', 'keyword extractor', 'content optimization', 'seo keywords', 'keyword tool', 'content analysis'],
  },
  {
    id: 'meta-tags',
    name: 'Meta Tags Generator',
    description: 'Create comprehensive SEO and social media preview tags for your website',
    category: 'seo',
    icon: 'Tags',
    path: '/tools/meta-tags',
    tags: ['meta tags', 'seo tags', 'open graph', 'twitter cards', 'meta description', 'meta title', 'seo generator'],
  },
  {
    id: 'opengraph',
    name: 'Open Graph Generator',
    description: 'Create social media preview tags for Facebook, Twitter, and LinkedIn',
    category: 'seo',
    icon: 'Share2',
    path: '/tools/opengraph',
    tags: ['open graph', 'og tags', 'social media', 'facebook preview', 'twitter card', 'linkedin preview', 'social sharing'],
  },
  {
    id: 'robots',
    name: 'Robots.txt Generator',
    description: 'Define crawling policies and control search engine access to your website',
    category: 'seo',
    icon: 'Bot',
    path: '/tools/robots',
    tags: ['robots.txt', 'crawler', 'seo', 'search engine', 'crawl policy', 'block bots', 'website indexing'],
  },
  {
    id: 'sitemap',
    name: 'XML Sitemap Generator',
    description: 'Create valid XML sitemaps to help search engines discover and index your website pages',
    category: 'seo',
    icon: 'Network',
    path: '/tools/sitemap',
    tags: ['sitemap', 'xml sitemap', 'seo', 'sitemap generator', 'google sitemap', 'search engine', 'website index'],
  },
  {
    id: 'url-slug',
    name: 'URL Slug Generator',
    description: 'Convert text into clean, readable, and search engine optimized URL slugs',
    category: 'seo',
    icon: 'Link',
    path: '/tools/url-slug',
    tags: ['url slug', 'slug generator', 'seo url', 'clean url', 'permalink', 'url optimization', 'friendly url'],
  },
  {
    id: 'base64',
    name: 'Base64 Converter',
    description: 'Encode and decode text to and from Base64 format',
    category: 'developer',
    icon: 'ArrowLeftRight',
    path: '/tools/base64',
    tags: ['base64', 'encode', 'decode', 'base64 converter', 'text encoding', 'base64 online', 'developer tool'],
  },
  {
    id: 'cron',
    name: 'Cron Expression Generator',
    description: 'Build and validate cron expressions with live human-readable descriptions',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/cron',
    tags: ['cron', 'cron generator', 'scheduler', 'cron expression', 'crontab', 'job scheduler', 'developer tool'],
  },
  {
    id: 'encryption',
    name: 'Text Encryption',
    description: 'Encrypt and decrypt text using a secret key with XOR cipher',
    category: 'developer',
    icon: 'Lock',
    path: '/tools/encryption',
    tags: ['encryption', 'decrypt', 'cipher', 'text encryption', 'xor cipher', 'secret key', 'developer tool'],
  },
  {
    id: 'html-editor',
    name: 'HTML Editor',
    description: 'Write and preview HTML with a live side-by-side editor',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/html-editor',
    tags: ['html', 'html editor', 'live preview', 'web development', 'html code', 'frontend tool', 'developer tool'],
  },
  {
    id: 'json',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data with error highlighting',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json',
    tags: ['json', 'json formatter', 'json validator', 'json minifier', 'json parser', 'developer tool', 'data formatting'],
  },
  {
    id: 'jwt-debugger',
    name: 'JWT Debugger',
    description: 'Decode and inspect JSON Web Tokens to view headers and payloads',
    category: 'developer',
    icon: 'Key',
    path: '/tools/jwt-debugger',
    tags: ['jwt', 'json web token', 'jwt decoder', 'jwt debugger', 'token inspector', 'developer tool', 'authentication'],
  },
  {
    id: 'regex',
    name: 'Regex Tester',
    description: 'Test regular expressions against sample text with match highlighting',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex',
    tags: ['regex', 'regular expression', 'regex tester', 'regex validator', 'pattern matching', 'developer tool'],
  },
  {
    id: 'strip-html',
    name: 'HTML Stripper',
    description: 'Remove all HTML tags and convert content to plain text',
    category: 'developer',
    icon: 'Eraser',
    path: '/tools/strip-html',
    tags: ['html stripper', 'remove html tags', 'plain text', 'html to text', 'clean text', 'developer tool'],
  },
  {
    id: 'compressor',
    name: 'File Compressor',
    description: 'Compress files and folders into ZIP archives directly in your browser',
    category: 'file',
    icon: 'Minimize2',
    path: '/tools/compressor',
    tags: ['file compressor', 'zip', 'compress', 'archive', 'zip creator', 'file tool'],
  },
  {
    id: 'extractor',
    name: 'ZIP Extractor',
    description: 'Extract files from ZIP archives directly in your browser',
    category: 'file',
    icon: 'FileArchive',
    path: '/tools/extractor',
    tags: ['zip extractor', 'unzip', 'extract', 'archive', 'zip opener', 'file tool'],
  },
  {
    id: 'renamer',
    name: 'Batch File Renamer',
    description: 'Rename multiple files at once with find-and-replace, numbering, and case options',
    category: 'file',
    icon: 'FileEdit',
    path: '/tools/renamer',
    tags: ['batch renamer', 'rename files', 'file rename', 'bulk rename', 'file tool'],
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write Markdown with a live side-by-side preview, syntax highlighting, and file upload/download',
    category: 'markdown',
    icon: 'FileText',
    path: '/tools/markdown-editor',
    tags: ['markdown', 'markdown editor', 'md editor', 'live preview', 'text editor', 'writing tool'],
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown syntax to clean, ready-to-use HTML code',
    category: 'markdown',
    icon: 'Code',
    path: '/tools/markdown-to-html',
    tags: ['markdown', 'html', 'markdown converter', 'md to html', 'web development', 'developer tool'],
  },
  {
    id: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create Markdown tables with an interactive editor, alignment options, and live preview',
    category: 'markdown',
    icon: 'Table',
    path: '/tools/markdown-table-generator',
    tags: ['markdown', 'table', 'markdown table', 'table generator', 'developer tool', 'writing tool'],
  },
  {
    id: 'combine-markdown',
    name: 'Combine Markdown',
    description: 'Merge multiple Markdown files into one document with custom separators',
    category: 'markdown',
    icon: 'FilePlus',
    path: '/tools/combine-markdown',
    tags: ['markdown', 'combine', 'merge markdown', 'bulk markdown', 'developer tool', 'writing tool'],
  },
  {
    id: 'markdown-cheatsheet',
    name: 'Markdown Cheatsheet',
    description: 'A quick reference guide for all common Markdown syntax with copy-to-clipboard support',
    category: 'markdown',
    icon: 'Book',
    path: '/tools/markdown-cheatsheet',
    tags: ['markdown', 'cheatsheet', 'reference', 'syntax guide', 'developer tool', 'writing tool'],
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    description: 'Resize images in your browser',
    category: 'image',
    icon: 'Maximize',
    path: '/tools/image-resize',
    tags: ['image', 'resize', 'edit', 'image resizer online', 'resize image online', 'photo resizer', 'online image editor'],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images by adjusting quality and format, all in your browser',
    category: 'image',
    icon: 'Minimize2',
    path: '/tools/image-compressor',
    tags: ['image', 'compress', 'compress image', 'reduce image size', 'optimize image', 'image optimizer'],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between JPEG, PNG, WebP, BMP, and GIF formats in your browser',
    category: 'image',
    icon: 'ArrowRightLeft',
    path: '/tools/image-converter',
    tags: ['image', 'convert', 'image converter', 'format change', 'jpg to png', 'png to webp', 'image tool'],
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to custom dimensions using HTML5 Canvas, completely in your browser',
    category: 'image',
    icon: 'Crop',
    path: '/tools/image-cropper',
    tags: ['image', 'crop', 'image cropper', 'cut image', 'photo crop', 'resize crop', 'image tool'],
  },
  {
    id: 'color-distance',
    name: 'Color Distance',
    description: 'Calculate color distances using Euclidean, Manhattan, and Delta E metrics',
    category: 'color',
    icon: 'Ruler',
    path: '/tools/color-distance',
    tags: ['color', 'distance', 'delta e', 'color comparison', 'design tool', 'color theory'],
  },
  {
    id: 'color-extractor',
    name: 'Color Extractor',
    description: 'Extract colors from images using an eyedropper tool with canvas pixel sampling',
    category: 'color',
    icon: 'Pipette',
    path: '/tools/color-extractor',
    tags: ['color', 'extract', 'palette', 'eyedropper', 'image colors', 'design tool'],
  },
  {
    id: 'color-harmony',
    name: 'Color Harmony',
    description: 'Generate color harmonies: complementary, analogous, triadic, split-complementary, tetradic, and monochromatic',
    category: 'color',
    icon: 'SwatchBook',
    path: '/tools/color-harmony',
    tags: ['color', 'harmony', 'palette', 'color scheme', 'design tool', 'color theory'],
  },
  {
    id: 'color-mixer',
    name: 'Color Mixer',
    description: 'Mix two colors with an adjustable ratio to find intermediate shades',
    category: 'color',
    icon: 'Palette',
    path: '/tools/color-mixer',
    tags: ['color', 'mix', 'blend', 'interpolate', 'design tool', 'color theory'],
  },
  {
    id: 'color-name-finder',
    name: 'Color Name Finder',
    description: 'Identify the name of any color — finds the closest of the 148 CSS named colors to any hex value, with the nearest alternatives',
    category: 'color',
    icon: 'Type',
    path: '/tools/color-name-finder',
    tags: ['color', 'name', 'color names', 'identify color', 'design tool', 'color theory'],
  },
  {
    id: 'color-temperature',
    name: 'Color Temperature',
    description: 'Convert Kelvin temperature values to RGB and hex colors',
    category: 'color',
    icon: 'Thermometer',
    path: '/tools/color-temperature',
    tags: ['color', 'temperature', 'kelvin', 'white balance', 'design tool', 'color theory'],
  },
  {
    id: 'colorblind-simulator',
    name: 'Colorblind Simulator',
    description: 'Simulate how images appear to people with different types of color blindness',
    category: 'color',
    icon: 'Eye',
    path: '/tools/colorblind-simulator',
    tags: ['color', 'accessibility', 'colorblind', 'vision', 'a11y', 'design tool'],
  },

  // Audio Tools
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    description: 'Convert between MP3, WAV, FLAC, AAC, and OGG formats',
    category: 'audio',
    icon: 'ArrowRightLeft',
    path: '/tools/audio-converter',
    tags: ['audio', 'convert', 'mp3', 'wav', 'flac', 'format'],
  },
  {
    id: 'audio-trimmer',
    name: 'Audio Trimmer',
    description: 'Trim and cut audio files with precision',
    category: 'audio',
    icon: 'Scissors',
    path: '/tools/audio-trimmer',
    tags: ['audio', 'trim', 'cut', 'edit', 'clip', 'audio trimmer online', 'trim audio online', 'cut audio online', 'online audio editor'],
  },
  {
    id: 'audio-merger',
    name: 'Audio Merger',
    description: 'Combine multiple audio tracks into one file',
    category: 'audio',
    icon: 'GitMerge',
    path: '/tools/audio-merger',
    tags: ['audio', 'merge', 'combine', 'join', 'tracks', 'merge audio online', 'combine audio files', 'audio joiner', 'online audio merger'],
  },
  {
    id: 'volume-adjuster',
    name: 'Volume Adjuster',
    description: 'Increase or decrease audio volume levels',
    category: 'audio',
    icon: 'Volume2',
    path: '/tools/volume-adjuster',
    tags: ['audio', 'volume', 'gain', 'loudness', 'normalize', 'adjust audio volume', 'volume booster', 'audio volume changer', 'online volume tool'],
  },
  {
    id: 'audio-reverser',
    name: 'Audio Reverser',
    description: 'Reverse audio playback for creative effects',
    category: 'audio',
    icon: 'Undo2',
    path: '/tools/audio-reverser',
    tags: ['audio', 'reverse', 'backward', 'effect', 'reverse audio online', 'play audio backwards', 'audio reverse effect', 'online audio reverser'],
  },
  {
    id: 'audio-compressor',
    name: 'Audio Compressor',
    description: 'Reduce audio file size while maintaining quality',
    category: 'audio',
    icon: 'Minimize2',
    path: '/tools/audio-compressor',
    tags: ['audio', 'compress', 'reduce', 'size', 'optimize', 'compress audio online', 'reduce audio size', 'audio file compressor', 'online audio compressor'],
  },
  {
    id: 'speed-changer',
    name: 'Speed & Pitch',
    description: 'Adjust playback speed and pitch independently',
    category: 'audio',
    icon: 'Gauge',
    path: '/tools/speed-changer',
    tags: ['audio', 'speed', 'tempo', 'pitch', 'playback', 'change audio speed', 'audio pitch changer', 'speed up audio', 'slow down audio'],
  },
  {
    id: 'audio-splitter',
    name: 'Audio Splitter',
    description: 'Split audio into multiple segments by duration',
    category: 'audio',
    icon: 'Split',
    path: '/tools/audio-splitter',
    tags: ['audio', 'split', 'segment', 'chapters', 'parts'],
  },
  {
    id: 'fade-in-out',
    name: 'Fade In / Out',
    description: 'Add smooth fade transitions to audio tracks',
    category: 'audio',
    icon: 'Activity',
    path: '/tools/fade-in-out',
    tags: ['audio', 'fade', 'transition', 'smooth', 'effect'],
  },
  {
    id: 'audio-equalizer',
    name: 'Audio Equalizer',
    description: 'Adjust bass, mid, and treble frequency bands',
    category: 'audio',
    icon: 'SlidersHorizontal',
    path: '/tools/audio-equalizer',
    tags: ['audio', 'equalizer', 'eq', 'bass', 'treble', 'frequency'],
  },
  {
    id: 'channel-mixer',
    name: 'Channel Mixer',
    description: 'Convert between stereo and mono channels',
    category: 'audio',
    icon: 'AudioLines',
    path: '/tools/channel-mixer',
    tags: ['audio', 'channel', 'stereo', 'mono', 'mix'],
  },
  {
    id: 'silence-remover',
    name: 'Silence Remover',
    description: 'Automatically detect and cut out silent sections from audio recordings',
    category: 'audio',
    icon: 'VolumeX',
    path: '/tools/silence-remover',
    tags: ['audio', 'silence', 'remove', 'podcast', 'trim', 'auto'],
  },
  {
    id: 'loudness-normalizer',
    name: 'Loudness Normalizer',
    description: 'Normalize audio to broadcast loudness standards like -14 or -23 LUFS',
    category: 'audio',
    icon: 'Activity',
    path: '/tools/loudness-normalizer',
    tags: ['audio', 'loudness', 'normalize', 'lufs', 'broadcast', 'podcast'],
  },
  {
    id: 'voice-isolator',
    name: 'Voice Isolator',
    description: 'Remove center-panned vocals from stereo tracks for karaoke or backing tracks',
    category: 'audio',
    icon: 'User',
    path: '/tools/voice-isolator',
    tags: ['audio', 'voice', 'karaoke', 'remove', 'vocal', 'backing'],
  },
  {
    id: 'audio-effects-studio',
    name: 'Audio Effects Studio',
    description: 'Apply echo, reverb, chorus, and flanger effects to audio tracks',
    category: 'audio',
    icon: 'Sparkles',
    path: '/tools/audio-effects-studio',
    tags: ['audio', 'effects', 'reverb', 'echo', 'chorus', 'flanger'],
  },
  {
    id: 'chapter-splitter',
    name: 'Chapter Splitter',
    description: 'Auto-split long audio files into chapters by detecting silence gaps — ideal for podcasts and audiobooks',
    category: 'audio',
    icon: 'BookOpen',
    path: '/tools/chapter-splitter',
    tags: ['audio', 'split', 'chapter', 'silence', 'podcast', 'audiobook', 'mp3 splitter', 'silence detection'],
  },
  {
    id: 'audio-metadata-editor',
    name: 'Audio Metadata Editor',
    description: 'View and edit ID3 tags, album art, and codec information',
    category: 'audio',
    icon: 'FileText',
    path: '/tools/audio-metadata-editor',
    tags: ['audio', 'metadata', 'id3', 'tags', 'album', 'edit'],
  },
  {
    id: 'audio-resampler',
    name: 'Audio Resampler',
    description: 'Change sample rate and bit depth for audio files',
    category: 'audio',
    icon: 'SlidersHorizontal',
    path: '/tools/audio-resampler',
    tags: ['audio', 'resample', 'sample-rate', 'bit-depth', 'quality'],
  },
  {
    id: 'ringtone-maker',
    name: 'Ringtone Maker',
    description: 'Trim, fade, and export audio as iPhone M4R or Android MP3 ringtones',
    category: 'audio',
    icon: 'Bell',
    path: '/tools/ringtone-maker',
    tags: ['audio', 'ringtone', 'm4r', 'mp3', 'iphone', 'android'],
  },

  // Video Tools
  {
    id: 'video-converter',
    name: 'Video Converter',
    description: 'Convert videos between MP4, AVI, MOV, WebM, MKV, and WMV formats',
    category: 'video',
    icon: 'ArrowRightLeft',
    path: '/tools/video-converter',
    tags: ['video', 'convert', 'format', 'mp4', 'avi', 'mov', 'webm', 'video converter online', 'mp4 converter', 'avi to mp4', 'free video converter', 'online video tool'],
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    description: 'Reduce video file size while maintaining quality with CRF presets',
    category: 'video',
    icon: 'Minimize2',
    path: '/tools/video-compressor',
    tags: ['video', 'compress', 'shrink', 'size', 'crf', 'video compressor online', 'compress video online', 'reduce video size', 'online video compressor'],
  },
  {
    id: 'video-trimmer',
    name: 'Video Trimmer',
    description: 'Cut and trim videos to desired length without re-encoding',
    category: 'video',
    icon: 'Scissors',
    path: '/tools/video-trimmer',
    tags: ['video', 'trim', 'cut', 'clip', 'length', 'video trimmer online', 'trim video online', 'cut video online', 'online video editor'],
  },
  {
    id: 'video-merger',
    name: 'Video Merger',
    description: 'Combine multiple videos into one file with format selection',
    category: 'video',
    icon: 'Layers',
    path: '/tools/video-merger',
    tags: ['video', 'merge', 'combine', 'join', 'concatenate', 'merge videos online', 'combine videos', 'video joiner', 'online video merger'],
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio',
    description: 'Extract audio track from video files to MP3, WAV, AAC, or FLAC',
    category: 'video',
    icon: 'Music',
    path: '/tools/extract-audio',
    tags: ['video', 'audio', 'extract', 'mp3', 'wav', 'aac', 'flac', 'extract audio from video', 'video to audio', 'audio extractor online', 'online audio extractor'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Convert video clips to animated GIF images',
    category: 'video',
    icon: 'FileImage',
    path: '/tools/video-to-gif',
    tags: ['video', 'gif', 'convert', 'animation', 'image', 'video to gif online', 'convert video to gif', 'video gif maker', 'online video gif converter'],
  },
  {
    id: 'video-speed-changer',
    name: 'Video Speed Changer',
    description: 'Speed up or slow down video playback with audio pitch correction',
    category: 'video',
    icon: 'Timer',
    path: '/tools/video-speed-changer',
    tags: ['video', 'speed', 'slow', 'fast', 'playback', 'timelapse', 'change video speed', 'slow down video', 'speed up video', 'online video speed'],
  },
  {
    id: 'aspect-ratio-converter',
    name: 'Aspect Ratio Converter',
    description: 'Resize videos for social platforms with pad or crop modes',
    category: 'video',
    icon: 'ScanLine',
    path: '/tools/aspect-ratio-converter',
    tags: ['video', 'aspect', 'ratio', 'resize', 'social', 'crop', 'pad', 'aspect ratio converter', 'video aspect ratio', 'resize video social', 'online aspect ratio video'],
  },
  {
    id: 'video-rotator',
    name: 'Video Rotator',
    description: 'Rotate or flip videos to fix orientation',
    category: 'video',
    icon: 'RotateCw',
    path: '/tools/video-rotator',
    tags: ['video', 'rotate', 'flip', 'orientation', 'mirror', 'rotate video online', 'flip video', 'fix video orientation', 'online video rotator'],
  },
  {
    id: 'mute-video',
    name: 'Mute Video',
    description: 'Remove audio track from video without re-encoding',
    category: 'video',
    icon: 'VolumeX',
    path: '/tools/mute-video',
    tags: ['video', 'mute', 'silent', 'remove', 'audio', 'mute video online', 'remove audio from video', 'silent video maker', 'online video muter'],
  },
  {
    id: 'gif-to-video',
    name: 'GIF to Video',
    description: 'Convert GIF images to MP4 or WebM for smaller file sizes',
    category: 'video',
    icon: 'Clapperboard',
    path: '/tools/gif-to-video',
    tags: ['gif', 'video', 'convert', 'mp4', 'webm', 'animation', 'gif to video online', 'convert gif to mp4', 'gif to mp4 converter', 'online gif converter'],
  },
  {
    id: 'video-screenshot',
    name: 'Video Screenshot',
    description: 'Extract a high-quality frame from any point in a video',
    category: 'video',
    icon: 'Camera',
    path: '/tools/video-screenshot',
    tags: ['video', 'screenshot', 'frame', 'image', 'extract', 'capture', 'video screenshot online', 'extract frame from video', 'video frame grabber', 'online video screenshot'],
  },
  {
    id: 'video-cropper',
    name: 'Video Cropper',
    description: 'Crop videos to custom dimensions or remove black bars',
    category: 'video',
    icon: 'Crop',
    path: '/tools/video-cropper',
    tags: ['video', 'crop', 'dimensions', 'trim', 'bars', 'video cropper', 'crop video', 'video trimmer', 'online video tool', 'crop video online', 'video cropper online', 'remove black bars video', 'online video cropper'],
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(tool => tool.category === categoryId);
}

export interface Subgroup {
  id: string;
  name: string;
  tools: Tool[];
}

// Ordered keyword rules used to cluster a category's tools into meaningful
// sub-sections so large categories don't render as one endless grid.
// A tool is placed into the first subgroup whose keywords match its id/name;
// anything unmatched falls into a trailing "Other" subgroup.
const SUBGROUP_RULES: Record<string, { name: string; keywords: string[] }[]> = {
  developer: [
    { name: "JSON", keywords: ["json"] },
    { name: "JWT", keywords: ["jwt"] },
    { name: "Regex", keywords: ["regex"] },
    { name: "Cron", keywords: ["cron"] },
    { name: "Docker", keywords: ["docker"] },
    { name: "SQL", keywords: ["sql"] },
    { name: "YAML, XML & TOML", keywords: ["yaml", "xml", "toml"] },
    { name: "GraphQL", keywords: ["gql", "graphql"] },
    { name: "HTML", keywords: ["html", "wysiwyg"] },
    { name: "Hashing", keywords: ["hash"] },
    { name: "Encoding", keywords: ["base64", "url-encoder", "data-uri", "html-entities"] },
    { name: "Network & IP", keywords: ["ip", "subnet", "mac-address", "port", "ssl", "http-status", "og-debugger"] },
    { name: "Cryptography", keywords: ["encryption"] },
    { name: "Device & Client", keywords: ["device", "user-agent", "keycode"] },
    { name: "Reference", keywords: ["memo", "cheat", "mime", "performance", "web-vitals", "media-query", "meta-tag", "js-logger", "text-compressor", "email-normalizer", "chmod"] },
    { name: "Converters", keywords: ["curl", "svg-jsx"] },
  ],
  pdf: [
    { name: "Merge & Split", keywords: ["merge", "split", "extract-pages", "organize", "delete-pages", "add-blank-page"] },
    { name: "Pages & Headers", keywords: ["page-numbers", "header-footer", "add-page-labels", "edit-bookmarks", "table-of-contents"] },
    { name: "Watermark & Background", keywords: ["add-watermark", "background-color"] },
    { name: "Transform", keywords: ["crop", "rotate", "adjust-colors", "invert-colors", "scanner-effect"] },
    { name: "Convert", keywords: ["jpg-to-pdf", "pdf-to-text"] },
    { name: "Optimize", keywords: ["compress-pdf", "remove-blank-pages", "remove-annotations"] },
    { name: "Sign", keywords: ["sign-pdf"] },
  ],
  audio: [
    { name: "Convert & Compress", keywords: ["audio-converter", "audio-compressor", "audio-resampler"] },
    { name: "Cut & Merge", keywords: ["audio-trimmer", "audio-splitter", "audio-merger", "chapter-splitter", "ringtone-maker", "silence-remover"] },
    { name: "Effects", keywords: ["audio-effects-studio", "fade-in-out", "audio-reverser", "speed-changer"] },
    { name: "Quality & Mixing", keywords: ["audio-equalizer", "channel-mixer", "loudness-normalizer", "volume-adjuster", "voice-isolator"] },
    { name: "Metadata", keywords: ["audio-metadata-editor"] },
  ],
  image: [
    { name: "Convert & Compress", keywords: ["image-converter", "image-compressor"] },
    { name: "Resize & Crop", keywords: ["image-resize", "image-cropper", "aspect-ratio", "svg-placeholder"] },
    { name: "CSS Generators", keywords: ["css-grid", "css-flexbox", "box-shadow", "glassmorphism", "gradient-studio"] },
    { name: "SVG", keywords: ["svg-optimizer", "svg-path"] },
    { name: "Color & Accessibility", keywords: ["color-palette", "contrast-checker", "color-blindness"] },
    { name: "Other", keywords: ["camera-recorder", "lottie-preview"] },
  ],
  text: [
    { name: "Case & Format", keywords: ["case-converter", "text-sorter", "line-numbers", "list-converter"] },
    { name: "Analyze", keywords: ["word-counter", "text-statistics", "readability-analyzer", "text-diff"] },
    { name: "Clean & Convert", keywords: ["text-cleaner", "slugify", "html-markdown", "markdown-html", "md-table-generator"] },
    { name: "Transform", keywords: ["text-repeater", "text-reverser", "numeronym", "nato-alphabet"] },
    { name: "Parse", keywords: ["phone-parser"] },
  ],
  video: [
    { name: "Convert & Compress", keywords: ["video-converter", "video-compressor", "gif-to-video", "video-to-gif"] },
    { name: "Cut & Merge", keywords: ["video-trimmer", "video-merger", "video-cropper", "video-screenshot", "extract-audio"] },
    { name: "Effects", keywords: ["video-rotator", "mute-video", "video-speed-changer", "aspect-ratio-converter"] },
  ],
  math: [
    { name: "Calculators", keywords: ["calculator", "math-evaluator", "fraction-calculator", "percentage-calculator"] },
    { name: "Health", keywords: ["bmi-calculator", "ideal-weight-calculator", "calorie-calculator"] },
    { name: "Finance", keywords: ["salary-calculator", "tip-calculator", "zakat-calculator", "gpa-calculator"] },
    { name: "Date & Time", keywords: ["age-calculator", "date-calculator", "datetime-hub", "eta-calculator"] },
    { name: "Tools", keywords: ["stopwatch"] },
  ],
  converter: [
    { name: "Encoding", keywords: ["base64-file", "base64-image-to-file", "text-binary", "text-unicode", "morse-code-converter"] },
    { name: "Date & Time", keywords: ["timestamp-converter", "time-zone-converter", "iso-formatter", "time-duration-converter"] },
    { name: "Numbers", keywords: ["integer-base-converter", "roman-numeral-converter"] },
    { name: "Validation", keywords: ["iban-validator"] },
    { name: "Network", keywords: ["ipv4-address-converter"] },
    { name: "Units", keywords: ["unit-converter", "temperature-converter"] },
  ],
  security: [
    { name: "Hashing", keywords: ["hash-text", "bcrypt", "hmac-generator"] },
    { name: "Encryption", keywords: ["aes-encryption", "rsa-generator", "string-obfuscator"] },
    { name: "Auth", keywords: ["jwt-generator", "basic-auth", "otp-generator"] },
    { name: "Passwords", keywords: ["password-generator", "password-strength"] },
    { name: "Keys & Certificates", keywords: ["bip39", "ssl-decoder"] },
    { name: "Other", keywords: ["pdf-integrity", "safelink-decoder"] },
  ],
  generator: [
    { name: "QR & Barcode", keywords: ["qr-generator", "wifi-qr", "barcode-generator", "barcode-studio"] },
    { name: "IDs & Tokens", keywords: ["uuid-generator", "ulid-generator", "token-generator", "random-number-generator"] },
    { name: "Text", keywords: ["lorem-ipsum", "ascii-text-drawer", "formal-email-generator", "emoji-picker"] },
    { name: "Documents", keywords: ["invoice-generator"] },
  ],
};

function slugifySubgroup(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

// Returns the subgroups for a category. Categories without explicit rules
// (or with very few tools) collapse into a single "All" subgroup so the
// UI can render them uniformly.
export function getSubgroups(categoryId: string): Subgroup[] {
  const categoryTools = getToolsByCategory(categoryId);
  const rules = SUBGROUP_RULES[categoryId];

  if (!rules || categoryTools.length <= 8) {
    return [{ id: "all", name: "All Tools", tools: categoryTools }];
  }

  const subgroups: Subgroup[] = [];
  const matched = new Set<string>();
  const other: Tool[] = [];

  for (const rule of rules) {
    const bucket: Tool[] = [];
    for (const tool of categoryTools) {
      if (matched.has(tool.id)) continue;
      const hay = `${tool.id} ${tool.name}`.toLowerCase();
      if (rule.keywords.some((kw) => hay.includes(kw))) {
        bucket.push(tool);
        matched.add(tool.id);
      }
    }
    if (bucket.length > 0) {
      subgroups.push({ id: slugifySubgroup(rule.name), name: rule.name, tools: bucket });
    }
  }

  for (const tool of categoryTools) {
    if (!matched.has(tool.id)) other.push(tool);
  }
  if (other.length > 0) {
    subgroups.push({ id: "other", name: "Other", tools: other });
  }

  return subgroups;
}

export function getToolById(id: string): Tool | undefined {
  return tools.find(tool => tool.id === id);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    tool =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
